[OPTIONS]
default = 1
font = Arial Black
size = 9
flags = 4
time = 10
words = Cry, shit, noob, trash, ez, mad, bad, raped

;--------------------- I N F O -------------------------
;	НАЗВАНИЕ И РАСШИРЕНИЕ ЭТОГО .ini файла НЕ МЕНЯТЬ!!!
;	команды:
;	/tdr - вкл/выкл
;	/tdreset - перезагрузить настройки из ini файла

;	*default: 0 - скрипт изначально отключен, 1 - включен
;	*flags: 1 жирный, 2 курсив, 4 обводка, 8 тень, 16 подчеркнутый, 32 зачеркнутый
;		пример: флаг = 1+4 = 5 - будет жирный текст с обводкой
;	*time - длительность движения и исчезновения текста (чем мнеьше значение - тем быстрее)
;	*words - слова, которые будт появляться при попадании. Перечислять через запятую
;
;by p1cador
;vk.com/id63306232
;------------------------------------------------------